# -*- coding: utf-8 -*-
"""codtech_task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YnZB26u64xEjg7ZtgXuIMfI29PNJUdG0
"""

import pandas as pd

data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
              'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    'Sales': [12000, 15000, 14000, 18000, 21000, 19000,
              23000, 25000, 22000, 27000, 30000, 32000]
}

df = pd.DataFrame(data)

df

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print(df.head())
print(df.info())
print(df.describe())

plt.figure(figsize=(10, 5))

plt.plot(df['Month'], df['Sales'], marker='o')

plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Sales')
plt.grid(True)

plt.show()

plt.figure(figsize=(10, 5))

plt.bar(df['Month'], df['Sales'])

plt.title('Monthly Sales Comparison')
plt.xlabel('Month')
plt.ylabel('Sales')

plt.show()

total_sales = df['Sales'].sum()
average_sales = df['Sales'].mean()

print("Total Sales:", total_sales)
print("Average Monthly Sales:", average_sales)

df['Category'] = df['Sales'].apply(
    lambda x: 'High' if x >= 25000
    else 'Medium' if x >= 18000
    else 'Low'
)

df