# -*- coding: utf-8 -*-
"""CodTech_task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kGfOb9Pb_RoX8VXbwrki9MW_s-am5s2E
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    'Day': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    'Temperature': [28, 30, 27, 29, 32, 31, 26],
    'Humidity': [70, 65, 80, 72, 60, 63, 85],
    'Rainfall': [10, 0, 15, 5, 0, 2, 20],
    'Weather': ['Rainy', 'Sunny', 'Rainy', 'Cloudy',
                'Sunny', 'Sunny', 'Rainy']
}

df = pd.DataFrame(data)

df

print(df.head())
print(df.info())
print(df.describe())

average_temperature = df['Temperature'].mean()

print("Average Temperature:", average_temperature, "°C")

max_temp = df.loc[df['Temperature'].idxmax()]
min_temp = df.loc[df['Temperature'].idxmin()]

print("Highest Temperature:")
print(max_temp)

print("\nLowest Temperature:")
print(min_temp)

plt.figure(figsize=(10, 5))

plt.plot(
    df['Day'],
    df['Temperature'],
    marker='o'
)

plt.title('Weekly Temperature Trend')
plt.xlabel('Day')
plt.ylabel('Temperature (°C)')
plt.grid(True)

plt.show()

plt.figure(figsize=(10, 5))

plt.bar(
    df['Day'],
    df['Humidity']
)

plt.title('Daily Humidity')
plt.xlabel('Day')
plt.ylabel('Humidity (%)')

plt.show()

plt.figure(figsize=(7, 5))

sns.countplot(
    data=df,
    x='Weather'
)

plt.title('Weather Condition Distribution')
plt.xlabel('Weather Condition')
plt.ylabel('Number of Days')

plt.show()

plt.figure(figsize=(8, 5))

sns.scatterplot(
    data=df,
    x='Temperature',
    y='Humidity'
)

plt.title('Temperature vs Humidity')
plt.xlabel('Temperature (°C)')
plt.ylabel('Humidity (%)')

plt.show()

rainiest_day = df.loc[df['Rainfall'].idxmax()]

print("Rainiest Day:")
print(rainiest_day)

print("Average Temperature:", round(df['Temperature'].mean(), 2), "°C")
print("Average Humidity:", round(df['Humidity'].mean(), 2), "%")
print("Total Rainfall:", df['Rainfall'].sum(), "mm")
print("Rainiest Day:", df.loc[df['Rainfall'].idxmax(), 'Day'])
print("Hottest Day:", df.loc[df['Temperature'].idxmax(), 'Day'])