# -*- coding: utf-8 -*-
"""CodTech_Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fee-42QuJsx15Ug3CBe8YaLy3zMGOZ0F
"""

!pip install textblob

import pandas as pd
from textblob import TextBlob

data = {
    'Customer_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Feedback': [
        'The product is excellent and very useful',
        'I am very happy with the service',
        'The delivery was fast and good',
        'The product quality is terrible',
        'I am disappointed with this product',
        'The service was okay',
        'Amazing product and great experience',
        'Very poor customer service',
        'The product is average',
        'I really love this product'
    ]
}

df = pd.DataFrame(data)

df

def get_sentiment(text):
    polarity = TextBlob(text).sentiment.polarity

    if polarity > 0:
        return 'Positive'
    elif polarity < 0:
        return 'Negative'
    else:
        return 'Neutral'

df['Sentiment'] = df['Feedback'].apply(get_sentiment)

df

sentiment_count = df['Sentiment'].value_counts()

print(sentiment_count)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(7, 5))

sns.countplot(
    data=df,
    x='Sentiment'
)

plt.title('Customer Feedback Sentiment Distribution')
plt.xlabel('Sentiment')
plt.ylabel('Number of Customers')

plt.show()

sentiment_percentage = (
    df['Sentiment']
    .value_counts(normalize=True) * 100
)

print(sentiment_percentage)

positive_feedback = df[df['Sentiment'] == 'Positive']

positive_feedback

negative_feedback = df[df['Sentiment'] == 'Negative']

negative_feedback

overall_sentiment = df['Sentiment'].mode()[0]

print("Overall Customer Sentiment:", overall_sentiment)